package com.metroair.job_card_management.domain.model

data class JobCard(
    val id: Int,
    val jobNumber: String,
    val customerName: String = "",
    val customerPhone: String = "",
    val customerEmail: String? = null,
    val customerAddress: String? = null,
    val title: String,
    val description: String?,
    val jobType: JobType,
    val status: JobStatus,
    val scheduledDate: String?,
    val scheduledTime: String?,
    val serviceAddress: String?,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val estimatedDuration: Int? = null, // minutes
    val travelDistance: Double? = null,
    val statusHistory: String? = null,
    val workPerformed: String? = null,
    val technicianNotes: String? = null,
    val issuesEncountered: String? = null,
    val customerSignature: String? = null,
    val beforePhotos: List<PhotoWithNotes>? = null,
    val afterPhotos: List<PhotoWithNotes>? = null,
    val otherPhotos: List<PhotoWithNotes>? = null,
    val requiresFollowUp: Boolean = false,
    val followUpNotes: String? = null,
    val customerRating: Int? = null,
    val customerFeedback: String? = null,
    val isSynced: Boolean = false,
    val lastSyncedAt: Long? = null
)
